# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Snapcast server
version: "0.0.1"
slug: snapcast-server
description: Snapcast server with Spotify connect support
url: "https://github.com/corneyl/hassio-addons/tree/main/snapcast-server"
# audio: true
host_network: true
privileged:
  - SYS_ADMIN
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
ports_description:
  1704/tcp: Snapcast client connections
  1705/tcp: Snapcast's control interface
  1780/tcp: Websocket connections to snapcast server
options:
  streams:
    streams: []
  buffer: 1000
  codec: flac
  send_to_muted: false
  sampleformat: "48000:16:2"
  spotify_name: "Home Assistant Sound System"
  log_level: info
schema:
  # Use nested option to force yaml editor on addon's config page
  streams:
    streams: ["str"]
  buffer: int
  codec: list(pcm|flac|vorbis|opus)
  send_to_muted: bool
  sampleformat: str
  spotify_name: str
  spotify_username: str?
  spotify_password: password?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
image: "ghcr.io/corneyl/{arch}-snapcast-server"
